/**
 * Actions
 */

export const SET_CONNECTED = 'SET_CONNECTED';
export const SET_DISCONNECTED = 'SET_DISCONNECTED';
export const SET_ERLANG_NODE_NAME = 'SET_ERLANG_NODE_NAME';
export const NEW_PROCESS = 'NEW_PROCESS';
export const END_PROCESS = 'END_PROCESS';
export const TOGGLE_MESSAGES = 'TOGGLE_MESSAGES';
export const SET_NODE_CONTENT = 'SET_NODE_CONTENT';
export const SET_TRACED_PROCESSES = 'SET_TRACED_PROCESSES';
export const ADD_MESSAGE_SENT = 'ADD_MESSAGE_SENT';
export const ADD_MESSAGE_RECEIVED = 'ADD_MESSAGE_RECEIVED';
