/**
 * Actions
 */

export const SET_ERLANG_NODE_NAME = 'SET_ERLANG_NODE_NAME';
export const TOGGLE_MESSAGES = 'TOGGLE_MESSAGES';
export const SET_NODE_CONTENT = 'SET_NODE_CONTENT';
export const ADD_MESSAGE_SENT = 'ADD_MESSAGE_SENT';
export const ADD_MESSAGE_RECEIVED = 'ADD_MESSAGE_RECEIVED';
